[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = [
    "bevy_dev_tools",
    "wav",
    "tiff",
]}
bevy_framepace = "0.18.1"
# pyo3 = { version = "0.24.0", features = ["auto-initialize"]}
rand = "0.9.0"
