[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = [
    "bevy_dev_tools",
    "wav",
    "tiff",
]}
bevy_kira_audio = "0.22.0"
rand = "0.9.0"
